### PR TITLE
improve MotorMonitor using GUILayout

### PR DESCRIPTION
**Pull request by llafuente**
I don't like the idea of adding Text anytime I need something to every scene in examples...

Also this is more readable.
I don't overwrite title or instructions but if you like the idea I could do it :)

### CODE REVIEW

**Comment by cjddmut** [comment]
In general I'm a bigger fan of using Unity UI and prefabbing it away so that it's easy to drop into a scene. But since this is just info for the example, I don't think it's important. I'd only prefer that it's consistent, either all Unity UI or all in OnGUI.

**Comment by llafuente** [comment]
Ok, all GUI then.

I will continue...

**Comment by llafuente** [comment]
Conflict introduced by: @b4b60691e063950984fdb583746c732795e618a6

can you merge it ? or i need to create another PR?

**Comment by cjddmut** [comment]
I'll resolve it soon.

**Comment by llafuente** [comment]
I solve it, and add position as Vector2, padding was a strange idea i had.
Also use TextArea for instructions, so ready to merge!

**Comment by cjddmut** [comment]
I'll get to merging this soon :) Sorry about that!

**Pull request closed without merging**
