### PR TITLE
Ladders (FreeMode state)

### PR DESCRIPTION
**Pull request by llafuente**
To implement ladders I use an "update yourself" state called: freeMode.

notes:
- `_motor.FreeModeEnter(String);` will stop any motor movement. And now you update the velocity by hand. (do not update normalizedXMovement, just velocity)
- `_motor.FreeModeExit();` set state to `Falling`.
- If you are in freeMode and touch the ground, you are in the `OnGround`.

I create a demo, to climb a ladder you must has up/down pressed inside the ladder.

I need feedback on this. I feel the API can be improved, I will try to demo ropes asap.

TODO
- [ ] animation
- [x] When ladder ends, player jumps a little and start falling, a One Way Platform at the top, should do the trick. While freeMode, OWP should not collide with the motor
- [x] Players can always leave the ladder by each side without jumping... Create a restricted area that the motor cannot leave.
- [ ] Handle rotated restricted areas
- [x] fix? jump at the top of the ladder
- [x] Disable Wall stick the OWP side?
- [x] remove Debug.Log / whitespaces cleanup
- [x] Static horizontal / vertical "rope/fence" example

Sorry for messing whitespaces, I will clean up the PR later.

### CODE REVIEW

**Comment by cjddmut** [comment]
I sure wish GitHub made commenting on files easier :P

**LaddersOnCollision.cs**
1. Since it's an example class, place it in the PC2D namespace to prevent polluting intellisense namespace of IDEs.

**PlatformerMotor2D.cs**
1. The flag value of FreeMode should be 0x40 not 0x32 (which is 110010 instead of 1000000).
2. Remove the setVelocity function as you can set the velocity property directly (which is more Unity style than having a set function).
3. I'm not sure the purpose of tracking a freeModeName? I'm not sure we care _why_ we are in FreeMode just that we are. I'd let whoever is using the motor determine that state and track that themselves.
4. As you mentioned in your post, there does appear to be some whitespace issues.
5. Remove Debug.Log statement.
6. Looking at the changes, I don't think FreeMode is a good fit to be part of the CollidedSurfaces enum. That enum represents what the motor is currently colliding against.

**PlayerController2D**
1. I'd make this line (and the one with x) more clear and const the values out.

```
y = y > 0 ? 5 : (y < 0 ? -5 : (0));
```

Overall I think this is a step in the right direction. Ladders/ropes are part of locomotion which I think can (or even should) fall under the responsibility of the motor. I'd consider approaching the implementation a little different. I'd make the motor more 'mode' friendly (can even have an enum for mode with Normal, FreeMode, and Dashing). In some ways the motor already has two modes, it has standard locomotion and dashing. I think following that pattern (or even making it more clear with modes) would be a good way to go about it and can avoid more 'if (_onLadder)' statements and just execute an update if the mode is FreeMode.

Good work and let me know if there is any confusion in my post!
C.J.

**Comment by llafuente** [comment]
Updated the demo, I think i got ladder implemented.
Just two minor issues
- if you jump the ladder, the side of the OWP at the top allow the player to WallStick... It's a bit annoying. Can this be disabled ?
- A little jump at the top

---

About your comments

> The flag value of FreeMode should be 0x40 not 0x32 (which is 110010 instead of 1000000).

Hexadecimal... Miss that. Fixed

> Looking at the changes, I don't think FreeMode is a good fit to be part of the CollidedSurfaces enum. That enum represents what the motor is currently colliding against.

Don't even use it atm. I will remove it.

> Remove the setVelocity function as you can set the velocity property directly (which is more Unity style than having a set function).

I cannot set that variable from outside, don't ask me why... i have to add that method... will review later.

> I'm not sure the purpose of tracking a freeModeName? I'm not sure we care why we are in FreeMode just that we are. I'd let whoever is using the motor determine that state and track that themselves.

freeModeName is for animation... 
FreeMode: I need a state that disable "gravity", now has also other implications:
OWP are ignored. I know you can do it swaping: `enableOneWayPlatforms`
but i think that while entering FreeMode you should enable/disable: OWP, jumping and maybe other things... still in progress

> As you mentioned in your post, there does appear to be some whitespace issues.

Yeah, maybe in another PR someone introduce linux line endings... And my editor do the rest converting those to windows.

> Remove Debug.Log statement.

ASAP :)

_PlayerController2D_

This "FreeMode" is not part of the motor configuration in my opinion, ladders are part of platformers but ropes? rails? cutscene movement?
isOnLadder is just a convenient way to store information in the motor, not necessarily tell you how to move in the ladder...  
I saw: `normalizedXMovement` but does not fit my purpose, also `normalizedYMovement` was missing... don't know... WDYT?

**Comment by llafuente** [comment]
It's review time.
@cjddmut PTAL

I add three different ladders.
- Ladder with restricted area: exit top-bottom (LEFT)
- Ladder that you can fall: exit top-bottom-left-right (RIGHT)
- Fence exit: no, you must jump to exit (MIDDLE)

**Comment by cjddmut** [comment]
Be sure to read all comments before taking any action :)
1. Place LadderZone.cs, LadderBody.cs, RestrictedArea.cs, and SpriteDebug.cs into the example folder (this way someone can easily delete the Example folder since neither of those files are necessary). 

```
public LadderZone ladderZone; //  why don't work!? { get; private set; } 
```

Remove the ';' after ladderZone.
1. If we've a good reason to add a 'normalizedYMovement' then let's just make that a Vector2 for x and y.
2. I'm still less fond of tracking the freeModeName with the motor :P It don't think it's the responsibility of the motor to track that information.
3. CollidedSurface is still no the right place for FreedomArea and Ladder. Those don't really represent what we're colliding against with our surroundings but more of what mode we're in. We should instead internally track what mode we're in. Somewhat to what I was mentioning earlier. I think buying into a mode system in the motor can work well for this.

Something like...

```
public enum Mode
{
    Normal,
    Dashing,
    Ladder
}
```

And in the code we can run certain code depending on the mode.
1. "freedomAreaEnter" and similar functions. This is a style thing, all functions start capitalized and none of the braces should be egyptian style.
2. Instead of tracking what kind of ladder it is in the motor it may make more sense to add a new component that is placed on ladders that tell us where the exits are and if jump can get us off. That way you can just add the component to each ladder and customize within the inspector.
3. There's a lot of 'if in freedom/lader mode' checks to get the right behavior. Check my previous comment about making the motor more mode friendly, I think it'll make it a lot easier, especially in the future.

I like the idea of the motor controlling this new mode. It makes sense since it's part of locomotion but I think a bit of refactoing will make the motor much more able to handle these special modes (and more modes in the future like ropes). I also may not be explaining my thoughts on the 'mode' idea very well through this comment section :)

**Comment by llafuente** [comment]
1 & 2 done

> If we've a good reason to add a 'normalizedYMovement' then let's just make that a Vector2 for x and y.

I consider this a breaking change, please do it yourself when bump a minor at least.

> I'm still less fond of tracking the freeModeName with the motor :P It don't think it's the responsibility of the motor to track that information

removed

> CollidedSurface is still no the right place for FreedomArea and Ladder. Those don't really represent what we're colliding against with our surroundings but more of what mode we're in. We should instead internally track what mode we're in. Somewhat to what I was mentioning earlier. I think buying into a mode system in the motor can work well for this.

I added `CollidedArea` to separate concepts.

> Instead of tracking what kind of ladder it is in the motor it may make more sense to add a new component that is placed on ladders that tell us where the exits are and if jump can get us off. That way you can just add the component to each ladder and customize within the inspector.

Made sense. But it will add a reasonable restriction, just one ladder at a time.

About your "Mode" idea... i don't know yet. I should be in another PR, this PR is already big enough, and this could a mayor breaking change in everybody's player controller....
I see many pros and cons... I need time to thinks about it.

---

I go on vacations today. I will be back 1th September. If you want to take over, do it, i will still read github but don't have a computer to develop...

**Comment by cjddmut** [comment]
We can get it figured out :)

I'm super busy preparing for an exhibition at the end of the month so I won't have any time to really spend on it til afterwards.

**Comment by llafuente** [comment]
squashed and cleaned.

I think we can merge and continue working on your "mode" idea in another PR that I volunteer to work :+1: 

btw: animation is missing on purpose, i will work on it later

**Comment by llafuente** [comment]
I'm testing some minor improvements, hold the merge a bit :)
I may even try to finish animation.

And Please create an issue to expose your idea about motor-modes so we can discuss it.

**Comment by llafuente** [comment]
I added support for ladders with two OWP and the floor (three floors)

Animation still missing...
@cjddmut I guess the ninja is free art, i cant find it, do you have more sprites? I really don't want to edit the images myself...

**Comment by cjddmut** [comment]
I created the ninja :P I can create more animations/sprites for it.

I'll take a look and if nothing pops up at me then I'll merge.

**Comment by cjddmut** [comment]
I'm not sure why the field 'oneWayPlatformsAreWalls' exists? What case is this trying to catch?

Once that's resolved I'll merge the pull request. I'm going to open up the issue (as you suggested) to implement ladders in a more mode like behavior for version 0.5. I also want us to think about how the interaction between the game dev and the motor with ladders and if there is a better way (my general goal is to make the motor as friendly to non-programmers as I can).

**Comment by cjddmut** [comment]
https://github.com/cjddmut/Unity-2D-Platformer-Controller/issues/32
https://github.com/cjddmut/Unity-2D-Platformer-Controller/issues/33

**Comment by llafuente** [comment]
> I'm not sure why the field 'oneWayPlatformsAreWalls' exists?

if enableOneWayPlatforms = false, then the OWP is a Solid (You can't climb up because controller got stuck below OWP)
With enableOneWayPlatforms = false && oneWayPlatformsAreWalls = false the collision is ignored. The Controller climb up, and when lave the ladder OWP and OWPAW are restored.

**Comment by llafuente** [comment]
@cjddmut something keep the PR from merging ?

**Comment by cjddmut** [comment]
Nope, just been busy. Merging.

**Pull request merged**
